### ISSUE TITLE
No battle triggered in 18_pop_travel_loyalisttrouble

### ISSUE THREAD

**Issue by StingrayOfSweden** [Nafeij/Nafeij-s-BS3-Fixpack#2]
One of the dialogue options in 18_pop_travel_loyalisttrouble is supposed to trigger a battle with Rugga loyalists.

From https://steamcommunity.com/sharedfiles/filedetails/?id=1586094823 :
_"Dogs! Leave them to me," Petrus says, mustering his guards. "Rugga's stink is all over this. Go make him end this now, or it'll keep happening. Do whatever it takes!"
"I'll get to Rugga after I deal with this, myself." = Battle
"Don't go easy on them, Petrus." = nothing_

But neither of the two options trigger a battle.

**Comment by Nafeij** [comment]
Noted, will work on it.
